/**
 * WARNING: This file is autogenerated by `build.js`
 */

import {Binary, Code, Double, Long, MinKey, MaxKey, ObjectID, Timestamp} from 'mongodb';
import Bulk from './lib/bulk';
import Collection from './lib/collection';
import Cursor from './lib/cursor';
import Database from './lib/database';

export {Bulk, Collection, Cursor, Database};

/**
 * Connect to a database
 */
declare function connect(connString: string, collectionNames?: Array<string>, options?: Object): Database;
export default connect;

export {Binary, Code, Double, Long, MinKey, MaxKey, ObjectID, Timestamp};
