/**
 * WARNING: This file is autogenerated by `build.js` from in `/schema/`bulk.js
 */

var Promise = require("promise");

module.exports = Bulk;
function Bulk(_parent) {
  this._parent = _parent;
}

Bulk.prototype.find = function find(query) {
  return this._parent.find(query);
};

Bulk.prototype.insert = function insert(doc) {
  return this._parent.insert(doc);
};

Bulk.prototype.tojson = function tojson() {
  return this._parent.tojson();
};

Bulk.prototype.toString = function toString() {
  return this._parent.toString();
};

Bulk.prototype.execute = function execute() {
  var _parent = this._parent
  return new Promise(function (resolve, reject) {
    _parent.execute(function (err, res) { err ? reject(err) : resolve(res) });
  });
};
