/**
 * WARNING: This file is autogenerated by `build.js` from in `/schema/`cursor.js
 */

import Promise = require("promise");

export default class Cursor {
  next(): Promise<Object>
  rewind(): Promise<any>
  toArray(): Promise<Array<Object>>
  map(mapfn: any): Promise<Array<any>>
  forEach(fn: any): void
  count(): Promise<number>
  size(): Promise<number>
  explain(): Promise<Object>
  destroy(): void
  batchSize(obj: Object): this
  hint(obj: Object): this
  limit(obj: Object): this
  maxTimeMS(obj: Object): this
  max(obj: Object): this
  min(obj: Object): this
  skip(obj: Object): this
  snapshot(obj: Object): this
  sort(obj: Object): this
}